### ISSUE TITLE
Features with negative values

### ISSUE THREAD

**Issue by rxjx** [UCLA-StarAI/LogisticCircuit#5]
I'm trying to use this for a different dataset so I generated a new tree. However, some of my features can take on negative values which doesn't work well with the np.log calls. For now I'm scaling them up to positive values but I keep getting :

"usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge"

and convergence is very slow. Am I doing something wrong with the scaling?

**Comment by YitaoLiang** [comment]
Hi,
   In terms of scaling, you would like to make sure the scale values are within [0,1]. Otherwise, the computation passes that feed features into linear regression could go wrong.
   In terms of convergence being slow, the implementation is largely borrowed from sklearn with small changes. On default, it should turn on multi-threads and you would like the number of threads to be not smaller than the number of classes in your dataset. It uses the change of parameters between iterations to determine convergence. It could be the threshold values are too small, so it never "converges" but actually your model's prediction values have essentially been stable. Another possibility to look out for is that  if in the "features" (i.e. not the raw data in your dataset, but the features extracted from the logistic circuits' computation pass. In other words, the features that feed into the logistic regression), the range of values are too large (i.e. some are super large, and some are super small), then floating number computations could be slow.

**Comment by rxjx** [comment]
Thanks for the details. My values are certainly within [0,1] after the scaling. I have only 1 class so threading should not be limiting. I'll have to look into the other possibilities you mentioned. I did increase the number of iterations for parameter optimization to 500 and that got rid of the warning but I still don't see much change in the accuracy numbers for train, valid, and test.

**Comment by YitaoLiang** [comment]
Hi, that does sound like, the values actually have been stable before "convergence". You can consider increasing the threshold number.
